### ISSUE TITLE
could dipper contract support fallback function ?

### ISSUE THREAD

**Issue by iavl** [Dipper-Labs/Dipper-Protocol#8]
Hi！

A contract can have exactly one unnamed function. This function cannot have arguments, cannot return anything and has to have external visibility. It is executed on a call to the contract if none of the other functions match the given function identifier (or if no data was supplied at all).

Furthermore, this function is executed whenever the contract receives plain DIP (without data). To receive DIP and add it to the total balance of the contract, the fallback function must be marked payable. If no such function exists, the contract cannot receive DIP through regular transactions and throws an exception.

Like any function, the fallback function can execute complex operations as long as there is enough gas passed on to it.

In the current version, transferring funds directly to the contract will not trigger the execution of the smart contract code.

In some scenarios, such as auctions or crowdfunding scenarios, fallback function may provide convenience for developers and users. For example, users can transfer DIP directly to contract through wallets and interact with dapps without using browser plug-ins.

**Comment by hot3246624** [comment]
Very good idea, we will add it

**Comment by cpucorecore** [comment]
good issue, this feature will be implemented in branch 'fallback'

**Comment by cpucorecore** [comment]
will be launched to spaceport for test

**Comment by cpucorecore** [comment]
# how to test:

## solidity contract for test:
```solidity
pragma solidity ^0.5.17;

contract A {
    int256 public i = 0;
    function() external payable {
        i++;
    }
}
```

## deploy contract:
```sh
dipcli vm create --from $(dipcli keys show -a sky) --code_file a.bin --amount 0pdip --args='' --abi_file a.abi -y
```

## test
```sh
# query the value of i in contract instance
dipcli q vm call $(dipcli keys show -a sky) dip1748v27r0r2eajfcn3z6pa3hr5dcuv2y6rru205 i ./a.abi --amount=0pdip --args=''

# make a fallback call
dipcli vm fallback --from $(dipcli keys show -a sky) --contract_addr dip1748v27r0r2eajfcn3z6pa3hr5dcuv2y6rru205 --amount 0pdip -y

# send to contract trigger fallback call
dipcli send --from $(dipcli keys show -a sky) --to dip1748v27r0r2eajfcn3z6pa3hr5dcuv2y6rru205 --amount 150pdip -y
```

**Comment by cpucorecore** [comment]
fallback functionality already launched to spaceport for Now
